# Generated by Django 3.2.13 on 2022-06-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acess_token', models.TextField()),
                ('acess_token_secret', models.TextField()),
            ],
        ),
    ]
