# Generated by Django 3.2.6 on 2021-11-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gif',
            name='display_url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='gif',
            name='expanded_url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='gif',
            name='gif_url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='gif',
            name='media_url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='gif',
            name='media_url_https',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='photo',
            name='media_url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='photo',
            name='media_url_https',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='place',
            name='url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='url',
            name='display_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='expanded_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=2048, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='analytics_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_background_image_url',
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_background_image_url_https',
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_banner_url',
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_image_url_https',
            field=models.URLField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='translator_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermention',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='media_url',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='video',
            name='media_url_https',
            field=models.URLField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_url',
            field=models.URLField(max_length=2048),
        ),
    ]
