# Generated by Django 3.2.6 on 2021-11-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_auto_20211129_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='content',
            field=models.CharField(max_length=2048),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=2048),
        ),
    ]
